spring:
  application:
    #muito importante definir o nome do app, a comunicação  feita por meio de nome do microsservio
    name: eurekaserver # poderia ser qualquer nome


server:
  port: 8761 # porta padrão do eurekaserver,  uma conveno

# configurando o client do eureka para no se auto registrar no discover server
eureka:
  client:
    register-with-eureka: false
    # buscar registros dos microsservios ? no. O gateway far isso,  seu papel
    fetch-registry: false


