spring:
  application:
    #muito importante definir o nome do app, a comunicação é feita por meio de nome do microsserviço
    name: eurekaserver # poderia ser qualquer nome


server:
  port: 8761 # porta padrão do eurekaserver, é uma convenção

# configurando o client do eureka para não se auto registrar no discover server
eureka:
  client:
    register-with-eureka: false
    # buscar registros dos microsserviços ? não. O gateway fará isso, é seu papel
    fetch-registrey: false


